version: '3.8'

services:
  patient-service:
    image: healthproject_lab_db:latest
    ports:
      - "8080:8080"

    networks:
      - my_network

  appointment-service:
    image: healthproject2_db:latest
    ports:
      - "8081:8081"

    networks:
      - my_network


  medicalRecords-service:
    image: healthproject3_db:latest
    ports:
      - "8082:8082"

    networks:
      - my_network


  pharmacy-service:
    image: healthproject4_db:latest
    ports:
      - "8083:8083"

    networks:
      - my_network


